<a href="https://colab.research.google.com/github/p4palu1/pythonProject/blob/main/eye_model_trial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**

In [ ]:
import numpy as np
import pandas as pd

**Importing the dataset**

In [ ]:
dataset = pd.read_csv('msnum.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[2 1 2 0]
 [5 2 0 0]
 [3 3 0 0]
 [5 0 0 0]
 [2 3 2 0]
 [6 0 0 0]
 [8 7 2 0]
 [5 0 0 0]
 [8 7 2 0]
 [8 0 0 0]
 [2 3 8 2]
 [5 8 0 0]
 [2 3 8 2]
 [5 0 0 0]
 [5 2 0 0]
 [0 0 0 0]
 [2 5 3 0]
 [6 0 0 0]
 [2 8 0 0]
 [5 1 0 0]
 [2 3 2 0]
 [8 0 0 0]
 [2 3 8 2]]


In [ ]:
print(y)

[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


**Encoding The independent variables**

**spliting the dataset into Training and test sets**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[2 5 3 0]
 [2 3 8 2]
 [2 3 2 0]
 [3 3 0 0]
 [2 8 0 0]
 [8 7 2 0]
 [5 0 0 0]
 [5 2 0 0]
 [5 2 0 0]
 [2 1 2 0]
 [0 0 0 0]
 [2 3 8 2]
 [8 0 0 0]
 [8 0 0 0]
 [8 7 2 0]
 [2 3 8 2]
 [5 8 0 0]
 [6 0 0 0]]


In [ ]:
print(X_test)

[[2 3 2 0]
 [6 0 0 0]
 [5 0 0 0]
 [5 0 0 0]
 [5 1 0 0]]


# **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4 0]
 [0 1]]


1.0

# **Support Vector Machine**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4 0]
 [0 1]]


1.0

# **Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[4 0]
 [0 1]]


1.0

# **Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[4 0]
 [0 1]]


1.0

# **Kernel SVM**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4 0]
 [0 1]]


1.0